apiVersion: v1
kind: Pod
metadata:
  namespace: training
  name: postgres
  labels:
    app-name: postgres
spec:
  containers:
    - name: postgres
      image: postgres:16-alpine
      ports:
        - containerPort: 5432
          name: db
      env:
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: admin
        - name: POSTGRES_DB
          value: training
---
apiVersion: v1
kind: Service
metadata:
  namespace: training
  name: postgres-service
spec:
  selector:
    app-name: postgres
  ports:
    - port: 5432
      targetPort: db

