apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: training
  name: storage-pv
spec:
  csi:
    driver:
    volumeHandle:

  hostPath:
    path: /tmp/storage
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
  # volumeMode: Filesystem