apiVersion: v1
kind: Service
metadata:
  name: echo-server-svc
  namespace: training
spec:
  selector:
    app-name: echo-server
  type: NodePort
  # clusterIP: 17.122.11.122
  # externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: http  #8080
      nodePort: 30000