apiVersion: v1
kind: Service
metadata:
  name: echo-server-svc
  namespace: training
spec:
  selector:
    app-name: echo-server
  # type: ClusterIP # default
  # clusterIP: 17.122.11.122
  ports:
    - port: 80
      targetPort: http  #8080