apiVersion: v1
kind: Pod
metadata:
  name: echo-server-pod
  namespace: training
  labels:
    version: "v1"
    training: "true"
    env: "dev"
spec:
  containers:
    - name: echo-server
      image: landrzejewski/echo-server-unhealthy:latest
      env:
        - name: version
          value: v1
      ports:
        - containerPort: 8080
          name: http
      resources:
        requests:
          memory: 64M
        limits:
          memory: 128M
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 30
        periodSeconds: 3
        failureThreshold: 3

         