apiVersion: v1
kind: ReplicationController
metadata:
  name: echo-server-rc
  namespace: training
spec:
  replicas: 10
  selector:
    app-name: echo-server
  template:
    metadata:
      namespace: training
      labels:
        app-name: echo-server
        env: prod
    spec:
      containers:
        - name: echo-server
          image: landrzejewski/echo-server #echo-server-unhealthy
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              memory: "64M"
              cpu: "250m"
            limits:
              memory: "128M"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 3
            failureThreshold: 3
